= Paramize

*WARNING: This library is still in early development, and the API is subject to change drastically*

A single header c++ library, that aims to create a framework for organizing template parameters. 

With paramize you can easily use template parameters in a similar fashion to struct literals. +
Instead of passing template parameters like normal function parameters; Like this:

----
Color<0, 0, 255, 0>
----

With 'Paramize' you can define the same color with something like this:

----
Color<ColorComp::B<255>>
----

We can pass any component of the color in any order. With this we don't have the problem of needing
to write the default values of components earlier in the template parameters again if I only want
to  change the value of the blue component.

== Example Usage:
---

See *'include/example.hpp'* for the entire example

[source, C++]
----
namespace ColorTags {
struct R;
struct G;
struct B;
struct A;
}

namespace ColorComp {
template<uint8_t value>
struct R : Paramize::ParamValue<ColorTags::R> {
    static constexpr uint8_t _value = value;
};

...

}

using ColorTagSet = Paramize::TagSet<ColorTags::R, ColorTags::G, ColorTags::B, ColorTags::A>;

template<Paramize::OptUniqueParam<ColorTagSet> C1 = void,
    Paramize::OptUniqueParam<ColorTagSet, C1> C2 = void,
    Paramize::OptUniqueParam<ColorTagSet, C1, C2> C3 = void,
    Paramize::OptUniqueParam<ColorTagSet, C1, C2, C3> C4 = void>
struct Color {
    static constexpr uint8_t _r
        = Paramize::tag_value<ColorTags::R, ColorComp::R<0>, C1, C2, C3, C4>::_value;
    static constexpr uint8_t _g 
        = Paramize::tag_value<ColorTags::G, ColorComp::G<0>, C1, C2, C3, C4>::_value;
    static constexpr uint8_t _b 
        = Paramize::tag_value<ColorTags::B, ColorComp::B<0>, C1, C2, C3, C4>::_value;
    static constexpr uint8_t _a 
        = Paramize::tag_value<ColorTags::A, ColorComp::A<0>, C1, C2, C3, C4>::_value;
};

using Blue = Color<ColorComp::B<255>>;
----

== Compiling Examples
---

To build all examples just use the zig compiler (built with the flags -Denable-llvm=true and 
-Duse-llvm=true) like you would normally build any zig project. 

*Disclaimer: currently there is only one example which cannot be built, but I will add some in the
future*
